create table User (
ID BIGINT auto_increment,
NAME VARCHAR(50),
PRIMARY KEY (ID),
FNUMBER VARCHAR(50)
);
INSERT INTO User (ID, NAME,FNUMBER ) VALUES (1, 'HELEN', '5840087');
INSERT INTO User (ID, NAME, FNUMBER) VALUES (2, 'MIKE', '3335553')